### ISSUE TITLE
PositionalEmbedding encoder/decoder

### ISSUE THREAD

**Issue by inspirit** [zhouhaoyi/Informer2020#106]
Hello,

I was wondering why do you use similar positional embedding for encoder and decoder.
In my understanding the labels input for decoder are shifted in position relative to input to encoder:
x_enc -> 0:seq_len
x_dec -> seq_len-label_len:seq_len+pred_len

but you do: 
x_enc -> 0:seq_len
x_dec -> 0:seq_len+pred_len

what is the reason behind?

**Comment by cookieminions** [comment]
Hi, 
x_enc-> 0:seq_len
x_dec-> 0:label_len+pred_len

We use positional encoding to express the positional relationship in one sequence so that self-attention can distinguish the context within the sequence. Encoder input and decoder input are two different sequences, and there are two self-attention module processing them, so we think is okay to using two independent positional encoding to make each self-attention understand the positional relationship in their own input sequence.

Of course, there is cross attention between encoder output and decoder input, so maybe you can try to use different positional encoding and it may get better results.

**Comment by inspirit** [comment]
thank you for explaining it.
