### ISSUE TITLE
Is it possible to share data files for generating tables of forecasting results?

### ISSUE THREAD

**Issue by mengcz13** [zhouhaoyi/Informer2020#125]
First of all, thanks for your outstanding work! I really enjoy reading the paper and the code.

One small request is that I wonder if it is possible to share the data files (outputs of the trained models, and the ground truth values) used when you generated tables of forecasting results (Table 1 & 2).

Since the model is unique compared to others in long time series forecasting, I feel it would be interesting to evaluate it under different granularities (e.g. comparing its performance on series aggregated by day/week). The data files would be of great help for evaluation with various granularities or different metrics.

Thanks!

**Comment by zhouhaoyi** [comment]
Thanks for your attention to our work. We have released the scripts to generate the results on Table 1 & 2, which could be found in the Informer2020/scripts. However, since our model has randomly run 5 times and we take their average as the final results. We are afraid that it may be hard for us to find the exact outputs of those results in Table 1 & 2. I guess you could use the example exp scripts to get the data files and comparing with other baselines with different granularities.
Meanwhile, we also perform a simple experiment about the granularities in the paper. You can refer to that part too.

**Comment by zhouhaoyi** [comment]
I will close this issue now.
