### ISSUE TITLE
about "circular" padding in conv op

### ISSUE THREAD

**Issue by rouniuyizu** [zhouhaoyi/Informer2020#18]
Hello, just wondering why "circular" padding is chosen for all the conv operations, including the projection of token embeddings?

**Comment by zhouhaoyi** [comment]
The circular padding is applied to force the whole model to treat the exact batch of time-series as a complete period (like a whole), which has been widely used in the CV field. Since we have a pyrimid-like structure with multiple decoder stacks, we believe it may help a little bit.
BTW, the projection of the time-series scalar is to be aligned with the embeddings' dimension.

**Comment by rouniuyizu** [comment]
Thank you,

**Comment by fjqfjqfjqfjqfjqfjqfjq** [comment]
Can you help me explain the difference between ”zero“ and “circular” in the padding mode? Have you tried zero padding mode in your paper, and what impact will it have on the results. Thank you very much.
