### ISSUE TITLE
A question about "attn.py"?

### ISSUE THREAD

**Issue by qinxiangyujiayou** [zhouhaoyi/Informer2020#19]
At “attn.py” "90 - 95 line" 
       "B, L, H, D = queries.shape
        _, S, _, _ = keys.shape

        queries = queries.view(B, H, L, -1)
        keys = keys.view(B, H, S, -1)
        values = values.view(B, H, S, -1)"

        why it use "view" but not "transpose"?

**Comment by cookieminions** [comment]
Because using `transpose` just swaps two dimensions while using `view` can  swap multiple dimensions.
To get more difference between view, reshape, transpose and permute in PyTorch, you can refer to this: https://jdhao.github.io/2019/07/10/pytorch_view_reshape_transpose_permute/ or https://medium.com/analytics-vidhya/pytorch-contiguous-vs-non-contiguous-tensor-view-understanding-view-reshape-73e10cdfa0dd
