### ISSUE TITLE
short input length, but long output length 

### ISSUE THREAD

**Issue by puzzlecollector** [zhouhaoyi/Informer2020#248]
@zhouhaoyi 
If I want to predict the next 2000 timesteps but if my input sequence length is only 500, then do you think this would affect performance a lot? In your opinion, do you think (input sequence length >= output sequence length) condition is necessary for a good performance in general?

**Comment by zhouhaoyi** [comment]
Thanks for your attention to our work! And I think this question is interesting.
In the definition of LSTF, we have not limited the forecasting to "the output length >> the input length". We just say that if the output length is larger enough then it can be considered as a LSTF problem.
Your problem actually depends on the condition of the dataset where you put your mode on. Take the ETT dataset as an example, we target predicting the oil temperature in a long run. The final results rely on how much data we collected. If we only have six months of data, we might be failed to predict the next 6-month's oil temperature because the ETT data is heavily seasonal. This is why we have to collect 12 months of data for the LSTF research. However, in your problem, if you think the previous 500 step contains the periodic pattern and trend for the next 2000 steps, you can seek a good performance. Otherwise, you would better collect more or bring external domain knowledge.

**Comment by puzzlecollector** [comment]
@zhouhaoyi 

I see thanks for the kind reply. I also wonder if you have tried testing the Informer on dataset with lots of noise, for example the Bitcoin price dataset? Do you suspect that the informer (or deep learning models in general) would not do very well when it comes to predicting the next n time steps for BTC?

**Comment by zhouhaoyi** [comment]
Actually, we are developing a new model for these kinds of datasets. Too sensitive to noise is one of the major drawbacks of the Transformer-based model. So the ProbSparse may help in this situation. You can search the following works based on Transformer in the forecasting task.

I hope we could bring a better solution earlier.

**Comment by puzzlecollector** [comment]
@zhouhaoyi  
Thank you for the kind answer. I will always keep an eye out on your work 👍
