### ISSUE TITLE
关于inverse output参数

### ISSUE THREAD

**Issue by guobinzhang2003** [zhouhaoyi/Informer2020#319]
楼主您好，请问如何理解inverse output参数，把缺省值从false改为true后性能提升很多，我做的是自定义数据集的二分类，预测后一天OT值(0/1), 还有就是逻辑回归我把损失函数变成交叉墒，效果不如mse，这也不太理解，希望楼主指点。

**Comment by zhouhaoyi** [comment]
请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？

**Comment by higherthanfly** [comment]
> 请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？

请问将inverse设置为true之后仍然结果没有还原，还是归一化的结果。这个是什么原因呢？要怎么解决呢？能否给一些提示？

**Comment by MountVoom** [comment]
> > 请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？
> 
> 请问将inverse设置为true之后仍然结果没有还原，还是归一化的结果。这个是什么原因呢？要怎么解决呢？能否给一些提示？

能否详细的描述一下您的问题或者给一些代码？或者您可以看一下dataloader或者_process_one_batch部分的对于反归一化处理的代码

**Comment by higherthanfly** [comment]
谢谢您的回复。这段时间已经将反归一的问题解决了，谢谢啦！












gbt
***@***.***


---原始邮件---
发件人: "Siyang ***@***.***&gt;
发送时间: 2023年3月28日(周二) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于inverse output参数 (Issue #319)




   
请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？
  
请问将inverse设置为true之后仍然结果没有还原，还是归一化的结果。这个是什么原因呢？要怎么解决呢？能否给一些提示？
  
能否详细的描述一下您的问题或者给一些代码？或者您可以看一下dataloader或者_process_one_batch部分的对于反归一化处理的代码

**Comment by loveciel** [comment]
> 谢谢您的回复。这段时间已经将反归一的问题解决了，谢谢啦！ gbt ***@***.***
> […](#)
> ---原始邮件--- 发件人: "Siyang ***@***.***&gt; 发送时间: 2023年3月28日(周二) 上午10:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于inverse output参数 (Issue #319) 请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？ 请问将inverse设置为true之后仍然结果没有还原，还是归一化的结果。这个是什么原因呢？要怎么解决呢？能否给一些提示？ 能否详细的描述一下您的问题或者给一些代码？或者您可以看一下dataloader或者_process_one_batch部分的对于反归一化处理的代码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好同学，我想请教下怎么解决归一化问题呀

**Comment by higherthanfly** [comment]
你可以看看归一化的原理，虽然预测后的数据是归一化的，但是可以再单独逆过程计算其原值，而不一定需要在函数里面改




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 中午12:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] 关于inverse output参数 (Issue #319)





  
谢谢您的回复。这段时间已经将反归一的问题解决了，谢谢啦！ gbt @.***
 …
 ---原始邮件--- 发件人: "Siyang @.&gt; 发送时间: 2023年3月28日(周二) 上午10:53 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于inverse output参数 (Issue #319) 请问可以提供一些数据sample吗？Inverse output将会把结果还原回去。如果是回归问题，而不是分类问题，应该使用mse会比交叉熵效果更好吧？ 请问将inverse设置为true之后仍然结果没有还原，还是归一化的结果。这个是什么原因呢？要怎么解决呢？能否给一些提示？ 能否详细的描述一下您的问题或者给一些代码？或者您可以看一下dataloader或者_process_one_batch部分的对于反归一化处理的代码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你好同学，我想请教下怎么解决归一化问题呀
