### ISSUE TITLE
复现性能问题

### ISSUE THREAD

**Issue by aptx1231** [zhouhaoyi/Informer2020#366]
请问按照scripts/目录下的脚本运行就可以复现出原文的性能吗？
为什么我运行的时候不同的itr，训练出来的结果差距较大呢？且性能达不到论文中的结果。
[etth1.log](https://github.com/zhouhaoyi/Informer2020/files/9468802/etth1.log)

**Comment by chouxiang777** [comment]
我使用WTH的数据，按照脚本参数中的：python -u main_informer.py --model informer --data WTH --features M --attn prob --d_layers 2 --e_layers 3 --itr 3 --label_len 168 --pred_len 24 --seq_len 168 --des 'Exp'   也没能复现论文中的性能，是我需要再重复跑几次嘛？同请教。感谢大佬分享的模型，为深度学习做出的贡献！

**Comment by LaterBetter** [comment]
> 

您好，您的问题解决了吗，我训练了100次，都是在0.5左右

**Comment by LaterBetter** [comment]
> 没能解决，也不明白哪里跟他做的不对，参数什么的用的都一样，我就没弄了，毕竟论文里的数据也不能太当真吧。 庄佳翔 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhouhaoyi/Informer2020" ***@***.***&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 下午5:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366) 您好，您的问题解决了吗，我训练了100次，都是在0.5左右 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

嗯的，谢谢您了

**Comment by chouxiang777** [comment]
老哥，你是研究生吗？准备研究深度学习这个方向呢？类似得模型，你还有好的推荐吗？我这边工作上需要做一些预测。




庄佳翔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366)





  
没能解决，也不明白哪里跟他做的不对，参数什么的用的都一样，我就没弄了，毕竟论文里的数据也不能太当真吧。 庄佳翔 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhouhaoyi/Informer2020" @.&gt;; 发送时间:&nbsp;2022年12月13日(星期二) 下午5:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366) 您好，您的问题解决了吗，我训练了100次，都是在0.5左右 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
嗯的，谢谢您了

**Comment by LaterBetter** [comment]
最近有autoformer，fedformer，nlinear这些效果比较好，之前的也有LSTM模型，我最近也是复现了autoformer



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月14日(周三) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366)




 老哥，你是研究生吗？准备研究深度学习这个方向呢？类似得模型，你还有好的推荐吗？我这边工作上需要做一些预测。 
 
 
 
 
 庄佳翔 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年12月13日(星期二) 下午5:05 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366) 
 
 
 
 
 
    
 没能解决，也不明白哪里跟他做的不对，参数什么的用的都一样，我就没弄了，毕竟论文里的数据也不能太当真吧。 庄佳翔 @.*** &amp;nbsp; 
  … 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "zhouhaoyi/Informer2020" @.&amp;gt;; 发送时间:&amp;nbsp;2022年12月13日(星期二) 下午5:01 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [zhouhaoyi/Informer2020] 复现性能问题 (Issue #366) 您好，您的问题解决了吗，我训练了100次，都是在0.5左右 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;gt; 
    
 嗯的，谢谢您了
