### ISSUE TITLE
BUG：Wrong att-mask in decoder

### ISSUE THREAD

**Issue by slczgwh** [zhouhaoyi/Informer2020#38]
A BUG when creating model:

https://github.com/zhouhaoyi/Informer2020/blob/a87092bc88aa2e97ac1b96478846e91543cc66aa/models/model.py#L50-L53

The BUG lead the cross-att in decoder using NO casual mask, while self-att using casual mask. Fortunately there is no information leak in informer, but still totally different with what you wrote in the paper.

**Comment by cookieminions** [comment]
Please refer to [Figure 1](https://github.com/zhouhaoyi/Informer2020/blob/main/img/informer.png). In decoder, we use masked multi-head prob-sparse self-attention and multi-head cross attention, so we use casual mask in self-attention and no casual mask in cross-attention. Since we utilize generative inference to generate prediction results, the causal mask in decoder is actually not critical. But you can also use mask in cross-attention ,and choose to use `prob attn` or `full attn` freely.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion and I will close this issue in 12h.
