### ISSUE TITLE
Question about _get_initial_context

### ISSUE THREAD

**Issue by victorxie996** [zhouhaoyi/Informer2020#88]
Hi, 

just wondering what is the rationale behind using V.cumsum(dim=-2) instead of V.mean(dim=-2) in line 78, 'attn.py'? Seems like the average value of V makes more sence and more consistent with the Algorithm 1 in the paper. 

Thanks in advance.

**Comment by victorxie996** [comment]
Thank you for the reply. However issue 23 focuses on discussing the no mask_flag case, when setting mask_flag=True, how come contex = V.cumsum(dim=-2)?

**Comment by cookieminions** [comment]
We simplified the implementation by using `cumsum` when setting `mask_flag=True`, because each encoder layer has a layernorm to normalize the values, so the impact is not significant.
You can also try to implement operation like `cummean` (because `mask_flag` is True, so you cannot use `mean` directly) in this part, we look forward to your pull request.

**Comment by QuantHao** [comment]
> We simplified the implementation by using `cumsum` when setting `mask_flag=True`, because each encoder layer has a layernorm to normalize the values, so the impact is not significant.
> You can also try to implement operation like `cummean` (because `mask_flag` is True, so you cannot use `mean` directly) in this part, we look forward to your pull request.

Great explanation! Casual mask need to be consider, thus cannot use mean.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I will close this issue now.
