### ISSUE TITLE
why concatenate axis of EncoderStack is -2?

### ISSUE THREAD

**Issue by QuantHao** [zhouhaoyi/Informer2020#93]
Hi, thanks for this thoughtful paper and sharing code base.

I am confused about concatenate axis using -2, which is sequence length L, at https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/encoder.py#L95

Based on #58 , @cookieminions says and I quotes "can make all Informers in InformerStack predict outputs with the same length" (at https://github.com/zhouhaoyi/Informer2020/issues/58#issuecomment-802907478). Should it be more reasonable to concate on channel axis, which is -1, instead of time axis as in current code?

For my understanding, EncoderStack seems to mimic Inception architecture (https://d2l.ai/chapter_convolutional-modern/googlenet.html#inception-blocks), thus would be more convincing to me if concate on channel axis.

Please correct me if I am wrong. Greatly appreciated in advance.

**Comment by cookieminions** [comment]
InformerStack is designed to concatenate all Encoder output on time axis, so that the InformerStack Encoder's output contains long-term and short-term information at the same time. The output length of each Encoder can be different, but their dimension must be the same, otherwise there will be problem at the cross attention in Decoder.

**Comment by QuantHao** [comment]
That makes sense. Thanks for reply.
